name: Run in Container Built from Dockerfile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      build:
        context: .
        dockerfile: Dockerfile
    defaults:
      run:
        # This ensures that the commands run in the repository folder
        working-directory: /github/workspace

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full commit history so that HEAD^ exists

      - name: List repository files (for debugging)
        run: ls -la /github/workspace

      - name: Run Git diff
        run: git diff HEAD^ HEAD

      - name: Show Salesforce CLI version
        run: sf --version
