name: Build and Test Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository so the Dockerfile and code are available.
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional but recommended for advanced build features).
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image using your Dockerfile.
      - name: Build Docker image
        run: docker build -t my-sf-node-image .

      # Step 4: Test that the Salesforce CLI is installed by printing its version.
      - name: Test Salesforce CLI version
        run: docker run --rm my-sf-node-image sf --version

      # Step 5: Run Git diff inside the Docker container.
      # This mounts the GitHub workspace into /app in the container so that git can access your repository.
      - name: Run Git diff in Docker container
        run: docker run --rm -v ${{ github.workspace }}:/app my-sf-node-image git diff HEAD^ HEAD
