name: SF CLI Container Workflow

on:
  push:
    branches:
      - main

jobs:
  run-sf-cli:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:2.77.1-slim

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Salesforce CLI Installation
        run: sf --version
