name: Install Salesforce CLI via npm
on: [push, pull_request]
jobs:
  install-sf-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
- name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
- name: Install Salesforce CLI
        run: npm install @salesforce/cli --global
- name: Verify installation
        run: sf --version
