name: Custom SF CLI Image Workflow

on:
  push:
    branches:
      - main

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
  generate-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Custom Docker Image
        id: cache-docker
        uses: actions/cache@v3
        with:
          path: custom-cli.tar
          key: custom-cli-image

      - name: Load or Build Custom Docker Image
        run: |
          if [ -f custom-cli.tar ]; then
            echo "Cached Docker image found. Loading image..."
            docker load -i custom-cli.tar
          else
            echo "No cached image found. Building custom Docker image..."
            docker build -t custom-sfdx:latest .
            docker save custom-sfdx:latest -o custom-cli.tar
          fi

      - name: Generate Manifest Using sfdx-git-delta
        run: |
          mkdir -p manifest
          docker run --rm \
            -v "$PWD":/workspace \
            -w /workspace \
            custom-sfdx:latest \
            sh -c "sfdx-git-delta --from HEAD~1 --to HEAD --output manifest/package.xml && cat manifest/package.xml"
