name: SF CLI Docker Workflow with sfdx-git-delta

on:
  push:
    branches:
      - main

jobs:
  generate-manifest:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (includes the Dockerfile)
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Cache the custom Docker image as a tar file.
      - name: Cache Custom Docker Image
        id: cache-docker
        uses: actions/cache@v3
        with:
          # Cache the tarball of the custom Docker image.
          path: cli-delta.tar
          key: cli-delta-image

      # Step 3: Load the cached image if available, otherwise build it.
      - name: Load or Build Custom Docker Image
        run: |
          if [ -f cli-delta.tar ]; then
            echo "Cached Docker image found. Loading image..."
            docker load -i cli-delta.tar
          else
            echo "No cached image found. Building custom Docker image..."
            docker build -t salesforce/cli-delta:latest .
            docker save salesforce/cli-delta:latest -o cli-delta.tar
          fi

      # Step 4: Run the container to generate and display the manifest.
      - name: Generate Manifest Using sfdx-git-delta
        run: |
          # Ensure the 'manifest' directory exists.
          mkdir -p manifest
          # Run the container with the repository mounted.
          docker run --rm \
            -v "$PWD":/workspace \
            -w /workspace \
            salesforce/cli-delta:latest \
            sh -c "sfdx-git-delta --from HEAD~1 --to HEAD --output manifest/package.xml && echo 'Generated manifest:' && cat manifest/package.xml"
