name: SFDMU Manual Workflow

# Allows the workflow to be manually triggered
on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'SFDMU Operation to perform (import/export)'
        required: true
        default: 'import'
      config_file:
        description: 'Path to SFDMU configuration file'
        required: false
        default: 'sfdmu.json'

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Salesforce CLI using the official GitHub Action
      - name: Install Salesforce CLI
        uses: salesforcecli/sfdx-cli@v2
        with:
          version: latest # You can specify a specific version if needed

      # Step 3: Install SFDMU
      - name: Install SFDMU
        run: npm install -g sfdmu

      # Step 4: Verify Installations (Optional)
      - name: Verify Salesforce CLI Installation
        run: sfdx --version

      - name: Verify SFDMU Installation
        run: sfdmu --version
