name: SFDMU Manual Workflow

# Allows the workflow to be manually triggered
on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'SFDMU Operation to perform (import/export)'
        required: true
        default: 'import'
      config_file:
        description: 'Path to SFDMU configuration file'
        required: false
        default: 'sfdmu.json'

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js LTS version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # Ensures the latest LTS version is installed

      # Step 3: Verify Node.js Installation (Optional)
      - name: Verify Node.js Installation
        run: node --version

      # Step 4: Install Salesforce CLI via npm
      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      # Step 5: Verify Salesforce CLI Installation (Optional)
      - name: Verify Salesforce CLI Installation
        run: sfdx --version

      # Step 6: Install SFDMU
      - name: Install SFDMU
        run: npm install -g sfdmu

      # Step 7: Verify SFDMU Installation (Optional)
      - name: Verify SFDMU Installation
        run: sfdmu --version
